<a href="https://colab.research.google.com/github/sarahbeatriz0205/tecnicas-analise-dados-tads/blob/main/meu_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conjunto de dados sobre venda de jogos

In [ ]:
import kagglehub
import pandas as pd
# uma alternativa pra eu ver o nome do arquivo -> import os > print(os.listdir(path))

path = kagglehub.dataset_download("bhushandivekar/video-game-sales-and-industry-data-1980-2024") # aqui ele baixa uma pasta com os dados
df = pd.read_csv(path + "/Video_Games_Sales_Cleaned.csv")
df.head(25)

Using Colab cache for faster access to the 'video-game-sales-and-industry-data-1980-2024' dataset.

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,2013.0
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,2014.0
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,2002.0
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,7.3,15.86,2013.0
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,2015.0
5,Call of Duty: Modern Warfare 3,X360,Shooter,Activision,Infinity Ward,8.7,14.82,2011.0
6,Call of Duty: Black Ops,X360,Shooter,Activision,Treyarch,8.8,14.74,2010.0
7,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,2018.0
8,Call of Duty: Black Ops II,X360,Shooter,Activision,Treyarch,8.4,13.86,2012.0
9,Call of Duty: Black Ops II,PS3,Shooter,Activision,Treyarch,8.0,13.80,2012.0
10,Call of Duty: Modern Warfare 2,X360,Shooter,Activision,Infinity Ward,9.5,13.53,2009.0
11,Call of Duty: WWII,PS4,Shooter,Activision,Sledgehammer Games,8.1,13.40,2017.0
12,Call of Duty: Modern Warfare 3,PS3,Shooter,Activision,Infinity Ward,8.8,13.35,2011.0
13,Grand Theft Auto III,PS2,Action,Rockstar Games,DMA Design,9.5,13.10,2001.0
14,Call of Duty: Black Ops,PS3,Shooter,Activision,Treyarch,8.7,12.67,2010.0
15,FIFA 18,PS4,Sports,EA Sports,EA Vancouver,8.3,11.80,2017.0
16,Grand Theft Auto IV,X360,Action,Rockstar Games,Rockstar North,10.0,11.09,2008.0
17,FIFA 17,PS4,Sports,Electronic Arts,EA Canada,8.9,10.94,2016.0
18,Call of Duty: Modern Warfare 2,PS3,Shooter,Activision,Infinity Ward,9.5,10.61,2009.0
19,Grand Theft Auto IV,PS3,Action,Rockstar Games,Rockstar North,10.0,10.57,2008.0
20,Call of Duty: Ghosts,X360,Shooter,Activision,Infinity Ward,6.9,10.41,2013.0
21,Call of Duty: Ghosts,PS3,Shooter,Activision,Infinity Ward,7.5,10.13,2013.0
22,Halo: Reach,X360,Shooter,Microsoft Game Studios,Bungie,9.3,9.97,2010.0
23,Halo 4,X360,Shooter,Microsoft Studios,343 Industries,7.3,9.96,2012.0
24,Call of Duty 4: Modern Warfare,X360,Shooter,Activision,Infinity Ward,9.6,9.41,2007.0

In [ ]:
df["title"].nunique()

12935

In [ ]:
df["console"].unique()

array(['PS3', 'PS4', 'PS2', 'X360', 'XOne', 'PC', 'PSP', 'Wii', 'PS',
       'DS', '2600', 'GBA', 'NES', 'XB', 'PSN', 'GEN', 'PSV', 'DC', 'N64',
       'SAT', 'SNES', 'GBC', 'GC', 'NS', '3DS', 'GB', 'WiiU', 'WS', 'VC',
       'NG', 'WW', 'SCD', 'PCE', 'XBL', '3DO', 'GG', 'OSX', 'Mob', 'PCFX'],
      dtype=object)

In [ ]:
df["total_sales"].head(10)

0    20.32
1    19.39
2    16.15
3    15.86
4    15.09
5    14.82
6    14.74
7    13.94
8    13.86
9    13.80
Name: total_sales, dtype: float64

In [ ]:
df["title"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 18832 entries, 0 to 18831
Series name: title
Non-Null Count  Dtype
--------------  -----
18832 non-null  object
dtypes: object(1)
memory usage: 147.3+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18832 entries, 0 to 18831
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         18832 non-null  object
 1   console       18832 non-null  object
 2   genre         18832 non-null  object
 3   publisher     18832 non-null  object
 4   developer     18832 non-null  object
 5   critic_score  18832 non-null  float64
 6   total_sales   18832 non-null  float64
 7   release_year  18832 non-null  float64
dtypes: float64(3), object(5)
memory usage: 1.1+ MB