<a href="https://colab.research.google.com/github/sarahbeatriz0205/tecnicas-analise-dados-tads/blob/main/meu_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conjunto de dados sobre venda de jogos

In [2]:
import kagglehub
import pandas as pd
# uma alternativa pra eu ver o nome do arquivo -> import os > print(os.listdir(path))

path = kagglehub.dataset_download("bhushandivekar/video-game-sales-and-industry-data-1980-2024") # aqui ele baixa uma pasta com os dados
df = pd.read_csv(path + "/Video_Games_Sales_Cleaned.csv")
df.head(25)

Downloading to /root/.cache/kagglehub/datasets/bhushandivekar/video-game-sales-and-industry-data-1980-2024/1.archive...

100%|██████████| 2.32M/2.32M [00:00<00:00, 118MB/s]

Extracting files...

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,2013.0
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,2014.0
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,2002.0
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,7.3,15.86,2013.0
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,2015.0
5,Call of Duty: Modern Warfare 3,X360,Shooter,Activision,Infinity Ward,8.7,14.82,2011.0
6,Call of Duty: Black Ops,X360,Shooter,Activision,Treyarch,8.8,14.74,2010.0
7,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,2018.0
8,Call of Duty: Black Ops II,X360,Shooter,Activision,Treyarch,8.4,13.86,2012.0
9,Call of Duty: Black Ops II,PS3,Shooter,Activision,Treyarch,8.0,13.80,2012.0
10,Call of Duty: Modern Warfare 2,X360,Shooter,Activision,Infinity Ward,9.5,13.53,2009.0
11,Call of Duty: WWII,PS4,Shooter,Activision,Sledgehammer Games,8.1,13.40,2017.0
12,Call of Duty: Modern Warfare 3,PS3,Shooter,Activision,Infinity Ward,8.8,13.35,2011.0
13,Grand Theft Auto III,PS2,Action,Rockstar Games,DMA Design,9.5,13.10,2001.0
14,Call of Duty: Black Ops,PS3,Shooter,Activision,Treyarch,8.7,12.67,2010.0
15,FIFA 18,PS4,Sports,EA Sports,EA Vancouver,8.3,11.80,2017.0
16,Grand Theft Auto IV,X360,Action,Rockstar Games,Rockstar North,10.0,11.09,2008.0
17,FIFA 17,PS4,Sports,Electronic Arts,EA Canada,8.9,10.94,2016.0
18,Call of Duty: Modern Warfare 2,PS3,Shooter,Activision,Infinity Ward,9.5,10.61,2009.0
19,Grand Theft Auto IV,PS3,Action,Rockstar Games,Rockstar North,10.0,10.57,2008.0
20,Call of Duty: Ghosts,X360,Shooter,Activision,Infinity Ward,6.9,10.41,2013.0
21,Call of Duty: Ghosts,PS3,Shooter,Activision,Infinity Ward,7.5,10.13,2013.0
22,Halo: Reach,X360,Shooter,Microsoft Game Studios,Bungie,9.3,9.97,2010.0
23,Halo 4,X360,Shooter,Microsoft Studios,343 Industries,7.3,9.96,2012.0
24,Call of Duty 4: Modern Warfare,X360,Shooter,Activision,Infinity Ward,9.6,9.41,2007.0

In [3]:
df["title"].nunique()

12935

In [4]:
df["console"].unique()

array(['PS3', 'PS4', 'PS2', 'X360', 'XOne', 'PC', 'PSP', 'Wii', 'PS',
       'DS', '2600', 'GBA', 'NES', 'XB', 'PSN', 'GEN', 'PSV', 'DC', 'N64',
       'SAT', 'SNES', 'GBC', 'GC', 'NS', '3DS', 'GB', 'WiiU', 'WS', 'VC',
       'NG', 'WW', 'SCD', 'PCE', 'XBL', '3DO', 'GG', 'OSX', 'Mob', 'PCFX'],
      dtype=object)

In [5]:
df["total_sales"].head(10)

0    20.32
1    19.39
2    16.15
3    15.86
4    15.09
5    14.82
6    14.74
7    13.94
8    13.86
9    13.80
Name: total_sales, dtype: float64

In [6]:
df["title"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 18832 entries, 0 to 18831
Series name: title
Non-Null Count  Dtype
--------------  -----
18832 non-null  object
dtypes: object(1)
memory usage: 147.3+ KB

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18832 entries, 0 to 18831
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         18832 non-null  object
 1   console       18832 non-null  object
 2   genre         18832 non-null  object
 3   publisher     18832 non-null  object
 4   developer     18832 non-null  object
 5   critic_score  18832 non-null  float64
 6   total_sales   18832 non-null  float64
 7   release_year  18832 non-null  float64
dtypes: float64(3), object(5)
memory usage: 1.1+ MB

In [8]:
df[['title', 'console', 'total_sales']]

                                             title console  total_sales
0                               Grand Theft Auto V     PS3        20.32
1                               Grand Theft Auto V     PS4        19.39
2                      Grand Theft Auto: Vice City     PS2        16.15
3                               Grand Theft Auto V    X360        15.86
4                        Call of Duty: Black Ops 3     PS4        15.09
...                                            ...     ...          ...
18827                                    Teslagrad    WiiU         0.00
18828                                  Open Season      XB         0.00
18829              The SpongeBob SquarePants Movie      PC         0.00
18830                  Santa Claus Saves the Earth     GBA         0.00
18831  Fossil League: Dino Tournament Championship      DS         0.00

[18832 rows x 3 columns]

- **query()**: Usado para filtrar DataFrames usando expressões booleanas baseadas em strings

In [14]:
df.query("console=='X360'")

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,7.3,15.86,2013.0
5,Call of Duty: Modern Warfare 3,X360,Shooter,Activision,Infinity Ward,8.7,14.82,2011.0
6,Call of Duty: Black Ops,X360,Shooter,Activision,Treyarch,8.8,14.74,2010.0
8,Call of Duty: Black Ops II,X360,Shooter,Activision,Treyarch,8.4,13.86,2012.0
10,Call of Duty: Modern Warfare 2,X360,Shooter,Activision,Infinity Ward,9.5,13.53,2009.0
...,...,...,...,...,...,...,...,...
18737,Captain Blood,X360,Action,Playlogic Game Factory,SeaWolf,7.3,0.00,2010.0
18775,Disorder 6,X360,Visual Novel,5pb,5pb. Games,7.3,0.00,2013.0
18810,Falling Skies: The Game,X360,Role-Playing,Little Orbit,Little Orbit,7.3,0.00,2016.0
18813,Final Fantasy XI: The Vana'diel Collection,X360,Role-Playing,Square Enix,Square Enix,7.3,0.00,2007.0
18818,Far East of Eden Ziria: Harukanaru Jipang,X360,Role-Playing,Hudson Soft,Hudson Soft,7.3,0.00,2006.0

- Mais recomendável usar **query()** para filtro de dados

In [20]:
df[(df['developer']=='Rockstar North')]

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,2013.0
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,2014.0
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,2002.0
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,7.3,15.86,2013.0
16,Grand Theft Auto IV,X360,Action,Rockstar Games,Rockstar North,10.0,11.09,2008.0
19,Grand Theft Auto IV,PS3,Action,Rockstar Games,Rockstar North,10.0,10.57,2008.0
28,Grand Theft Auto V,XOne,Action,Rockstar Games,Rockstar North,9.0,8.72,2014.0
338,Grand Theft Auto: Episodes from Liberty City,X360,Adventure,Rockstar Games,Rockstar North,9.0,2.60,2009.0
357,Rockstar Games Double Pack: Grand Theft Auto I...,XB,Action,Rockstar Games,Rockstar North,9.8,2.49,2003.0
478,Grand Theft Auto: Episodes from Liberty City,PS3,Adventure,Rockstar Games,Rockstar North,9.0,2.09,2010.0
541,Grand Theft Auto: San Andreas,XB,Action,Rockstar Games,Rockstar North,9.2,1.95,2005.0
656,Rockstar Games Double Pack: Grand Theft Auto I...,PS2,Action,Rockstar Games,Rockstar North,9.7,1.72,2003.0
1051,Manhunt,PS2,Action,Rockstar Games,Rockstar North,8.0,1.28,2003.0
1240,Grand Theft Auto: The Trilogy,PS2,Adventure,Rockstar Games,Rockstar North,7.3,1.14,2005.0
1542,Grand Theft Auto: San Andreas,PC,Action,Rockstar Games,Rockstar North,9.4,0.97,2005.0
7317,Manhunt,XB,Action,Rockstar Games,Rockstar North,7.7,0.19,2004.0
9047,Grand Theft Auto: San Andreas,XBL,Action,Rockstar Games,Rockstar North,7.3,0.13,2008.0
10540,Grand Theft Auto: Episodes from Liberty City,PC,Action,Rockstar Games,Rockstar North,7.3,0.09,2010.0
10584,Grand Theft Auto: The Trilogy,XB,Adventure,Rockstar Games,Rockstar North,7.3,0.09,2005.0
13987,Grand Theft Auto: Vice City,PC,Action,Rockstar Games,Rockstar North,9.0,0.04,2003.0
14462,Grand Theft Auto: The Trilogy,PC,Adventure,Rockstar Games,Rockstar North,7.3,0.03,2009.0
18505,Manhunt,PC,Action,Rockstar Games,Rockstar North,7.3,0.00,2004.0

- **value_counts():** Conta quantas vezes um elemento ocorre no Dataframe ou em um Series

In [16]:
df['genre'].value_counts()

genre
Action              2825
Sports              2581
Misc                1988
Adventure           1888
Role-Playing        1483
Shooter             1480
Racing              1422
Simulation          1116
Platform             949
Fighting             867
Strategy             818
Puzzle               719
Action-Adventure     264
Visual Novel         218
Music                147
MMO                   30
Party                 29
Education              4
Board Game             3
Sandbox                1
Name: count, dtype: int64

### Slicing
> tô usando errado, não entendi isso

> é para retornar a linha do meio do dataset

In [32]:
meio = len(df)//2
df.loc[meio:meio]

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
9416,Dorabase 2: Nettou Ultra Stadium,DS,Sports,Namco Bandai,Bandai Namco Games,7.3,0.12,2009.0

In [33]:
meio = len(df)//2
df.iloc[meio:meio+1]

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
9416,Dorabase 2: Nettou Ultra Stadium,DS,Sports,Namco Bandai,Bandai Namco Games,7.3,0.12,2009.0

### Ordenação com sort_values()

In [42]:
df.sort_values(by=['release_year'], ascending=True)

,title,console,genre,publisher,developer,critic_score,total_sales,release_year
1531,Air-Sea Battle,2600,Shooter,Atari,Atari,7.3,0.98,1977.0
1101,Combat,2600,Action,Atari,Atari,7.3,1.25,1977.0
5834,Indy 500,2600,Racing,Atari,Atari,7.3,0.27,1977.0
3855,Super Breakout,2600,Puzzle,Atari,Atari,7.3,0.44,1978.0
6776,Breakaway IV,2600,Puzzle,Sears,Atari,7.3,0.21,1978.0
...,...,...,...,...,...,...,...,...
8859,The Legend of Heroes: Trails of Cold Steel IV,PS4,Role-Playing,NIS America,Falcom,7.3,0.13,2020.0
16211,Let It Die,PS4,Action,GungHo,Grasshopper Manufacture,7.3,0.01,2020.0
18795,Aokana: Four Rhythm Across the Blue,NS,Visual Novel,Sprite,Sprite,7.3,0.00,2020.0
16238,Fujiko F. Fujio Characters: Great Assembly! Sl...,3DS,Action,Namco Bandai Games,Namco Bandai Games,7.3,0.01,2020.0
12955,Disaster Report 4 Plus: Summer Memories,PS4,Action-Adventure,NIS America,Granzella,7.3,0.05,2020.0

### Agrupamento com groupby()

In [46]:
df.groupby('genre')['critic_score'].sum() # somando os scores agrupando pelo gênero
df.groupby('genre')['critic_score'].min() # retornando os scores mínimos desse agrupamento

genre
Action              1.0
Action-Adventure    2.8
Adventure           2.5
Board Game          5.3
Education           7.3
Fighting            2.9
MMO                 6.5
Misc                2.0
Music               6.5
Party               4.0
Platform            1.5
Puzzle              3.5
Racing              2.0
Role-Playing        1.0
Sandbox             9.2
Shooter             1.7
Simulation          1.5
Sports              1.4
Strategy            2.5
Visual Novel        7.3
Name: critic_score, dtype: float64

- **reset_index():** Cria um novo dataframe baseado no agrupamento e no método usado

In [49]:
df.groupby('genre')['critic_score'].sum().reset_index() # cria um novo dataframe baseado no agrupamento e no método usado

               genre  critic_score
0             Action       20182.4
1   Action-Adventure        1940.3
2          Adventure       13715.8
3         Board Game          19.9
4          Education          30.1
5           Fighting        6316.2
6                MMO         219.2
7               Misc       14402.1
8              Music        1081.8
9              Party         197.7
10          Platform        6802.2
11            Puzzle        5227.9
12            Racing       10328.7
13      Role-Playing       10866.3
14           Sandbox           9.2
15           Shooter       10759.0
16        Simulation        8070.6
17            Sports       18911.7
18          Strategy        5982.3
19      Visual Novel        1593.1